/**
 * 전체 역 데이터 베이스 (Master Data)
 */
const stationMaster = {
  // === 1호선 역 데이터 (기존) ===
  yeoncheon: {
    name: "연천",
    lat: 38.1074,
    lng: 127.0754,
    line: "1호선",
    verified: false,
  },
  jeongok: {
    name: "전곡",
    lat: 38.0248,
    lng: 127.0656,
    line: "1호선",
    verified: false,
  },
  cheongsan: {
    name: "청산",
    lat: 37.9542,
    lng: 127.062,
    line: "1호선",
    verified: false,
  },
  soyosan: {
    name: "소요산",
    lat: 37.9272,
    lng: 127.0583,
    line: "1호선",
    verified: false,
  },
  dongducheon: {
    name: "동두천",
    lat: 37.9142,
    lng: 127.0573,
    line: "1호선",
    verified: false,
  },
  bosan: {
    name: "보산",
    lat: 37.9142,
    lng: 127.0573,
    line: "1호선",
    verified: false,
  },
  dongducheonJungang: {
    name: "동두천중앙",
    lat: 37.9038,
    lng: 127.057,
    line: "1호선",
    verified: false,
  },
  jihaeng: {
    name: "지행",
    lat: 37.892,
    lng: 127.0531,
    line: "1호선",
    verified: false,
  },
  deokjeong: {
    name: "덕정",
    lat: 37.8431,
    lng: 127.0612,
    line: "1호선",
    verified: false,
  },
  deokgye: {
    name: "덕계",
    lat: 37.8185,
    lng: 127.0461,
    line: "1호선",
    verified: false,
  },
  yangju: {
    name: "양주",
    lat: 37.7781,
    lng: 127.0438,
    line: "1호선",
    verified: false,
  },
  nokyang: {
    name: "녹양",
    lat: 37.7594,
    lng: 127.0423,
    line: "1호선",
    verified: false,
  },
  ganeung: {
    name: "가능",
    lat: 37.7483,
    lng: 127.0438,
    line: "1호선",
    verified: false,
  },
  uijeongbu: {
    name: "의정부",
    lat: 37.7385,
    lng: 127.0459,
    line: "1호선",
    verified: false,
  },
  hoeryong: {
    name: "회룡",
    lat: 37.7138,
    lng: 127.0468,
    line: "1호선",
    verified: false,
  },
  mangwolsa: {
    name: "망월사",
    lat: 37.7015,
    lng: 127.0456,
    line: "1호선",
    verified: false,
  },
  dobongsan: {
    name: "도봉산",
    lat: 37.6893,
    lng: 127.0462,
    line: "1호선",
    verified: false,
  },
  dobong: {
    name: "도봉",
    lat: 37.6796,
    lng: 127.0471,
    line: "1호선",
    verified: false,
  },
  banghak: {
    name: "방학",
    lat: 37.6675,
    lng: 127.0441,
    line: "1호선",
    verified: false,
  },
  changdong: {
    name: "창동",
    lat: 37.6532,
    lng: 127.0477,
    line: "1호선",
    verified: false,
  },
  nokcheon: {
    name: "녹천",
    lat: 37.6446,
    lng: 127.0487,
    line: "1호선",
    verified: false,
  },
  wolgye: {
    name: "월계",
    lat: 37.6289,
    lng: 127.0588,
    line: "1호선",
    verified: false,
  },
  kwangwoonUniv: {
    name: "광운대",
    lat: 37.6237,
    lng: 127.0618,
    line: "1호선",
    verified: false,
  },
  seokgye: {
    name: "석계",
    lat: 37.6151,
    lng: 127.0658,
    line: "1호선",
    verified: false,
  },
  sinimun: {
    name: "신이문",
    lat: 37.6034,
    lng: 127.0601,
    line: "1호선",
    verified: false,
  },
  oedaeap: {
    name: "외대앞",
    lat: 37.5962,
    lng: 127.0588,
    line: "1호선",
    verified: false,
  },
  hoegi: {
    name: "회기",
    lat: 37.5895,
    lng: 127.0575,
    line: "1호선",
    verified: false,
  },
  cheongnyangni: {
    name: "청량리",
    lat: 37.5802,
    lng: 127.0468,
    line: "1호선",
    verified: false,
  },
  jegiDong: {
    name: "제기동",
    lat: 37.578,
    lng: 127.0347,
    line: "1호선",
    verified: false,
  },
  sinseolDong: {
    name: "신설동",
    lat: 37.5753,
    lng: 127.0248,
    line: "1호선",
    verified: false,
  },
  dongmyo: {
    name: "동묘앞",
    lat: 37.5753,
    lng: 127.0248,
    line: "1호선",
    verified: false,
  },
  dongdaemun: {
    name: "동대문",
    lat: 37.5714,
    lng: 127.0098,
    line: "1호선",
    verified: false,
  },
  jongno5ga: {
    name: "종로5가",
    lat: 37.5709,
    lng: 127.0019,
    line: "1호선",
    verified: false,
  },
  jongno3ga: {
    name: "종로3가",
    lat: 37.5716,
    lng: 126.9918,
    line: "1호선",
    verified: false,
  },
  jonggak: {
    name: "종각",
    lat: 37.5702,
    lng: 126.983,
    line: "1호선",
    verified: false,
  },
  cityhall: {
    name: "시청",
    lat: 37.5702,
    lng: 126.983,
    line: "1호선",
    verified: false,
  },
  seoulStation: {
    name: "서울역",
    lat: 37.5547,
    lng: 126.9706,
    line: "1호선",
    verified: false,
  },
  namyeong: {
    name: "남영",
    lat: 37.541,
    lng: 126.9713,
    line: "1호선",
    verified: false,
  },
  yongsan: {
    name: "용산",
    lat: 37.5298,
    lng: 126.9648,
    line: "1호선",
    verified: false,
  },
  noryangjin: {
    name: "노량진",
    lat: 37.5138,
    lng: 126.9413,
    line: "1호선",
    verified: false,
  },
  daebang: {
    name: "대방",
    lat: 37.5133,
    lng: 126.9264,
    line: "1호선",
    verified: false,
  },
  singil: {
    name: "신길",
    lat: 37.5171,
    lng: 126.9101,
    line: "1호선",
    verified: false,
  },
  yeongdeungpo: {
    name: "영등포",
    lat: 37.5158,
    lng: 126.9076,
    line: "1호선",
    verified: false,
  },
  sindorim: {
    name: "신도림",
    lat: 37.5088,
    lng: 126.8912,
    line: "1호선",
    verified: false,
  },
  guro: {
    name: "구로",
    lat: 37.5031,
    lng: 126.882,
    line: "1호선",
    verified: false,
  },
  gasanDigitalComplex: {
    name: "가산디지털단지",
    lat: 37.4811,
    lng: 126.8826,
    line: "1호선",
    verified: false,
  },
  doksan: {
    name: "독산",
    lat: 37.4659,
    lng: 126.8954,
    line: "1호선",
    verified: false,
  },
  geumcheonGuOffice: {
    name: "금천구청",
    lat: 37.4516,
    lng: 126.8955,
    line: "1호선",
    verified: false,
  },
  seoksu: {
    name: "석수",
    lat: 37.435,
    lng: 126.9023,
    line: "1호선",
    verified: false,
  },
  gwanak: {
    name: "관악",
    lat: 37.4192,
    lng: 126.9084,
    line: "1호선",
    verified: false,
  },
  anyang: {
    name: "안양",
    lat: 37.4019,
    lng: 126.9226,
    line: "1호선",
    verified: false,
  },
  myeonghak: {
    name: "명학",
    lat: 37.3848,
    lng: 126.9356,
    line: "1호선",
    verified: false,
  },
  geumjeong: {
    name: "금정",
    lat: 37.3653,
    lng: 126.9355,
    line: "1호선",
    verified: false,
  },
  gunpo: {
    name: "군포",
    lat: 37.3533,
    lng: 126.9485,
    line: "1호선",
    verified: false,
  },
  dangjeong: {
    name: "당정",
    lat: 37.344,
    lng: 126.9482,
    line: "1호선",
    verified: false,
  },
  uiwang: {
    name: "의왕",
    lat: 37.3211,
    lng: 126.9543,
    line: "1호선",
    verified: false,
  },
  sungkyunkwanUniv: {
    name: "성균관대",
    lat: 37.3003,
    lng: 126.9708,
    line: "1호선",
    verified: false,
  },
  hwaseo: {
    name: "화서",
    lat: 37.2838,
    lng: 126.9898,
    line: "1호선",
    verified: false,
  },
  suwon: {
    name: "수원",
    lat: 37.2657,
    lng: 127.0,
    line: "1호선",
    verified: false,
  },
  seryu: {
    name: "세류",
    lat: 37.245,
    lng: 127.0132,
    line: "1호선",
    verified: false,
  },
  byeongjeom: {
    name: "병점",
    lat: 37.2069,
    lng: 127.033,
    line: "1호선",
    verified: false,
  },
  sema: {
    name: "세마",
    lat: 37.1873,
    lng: 127.0432,
    line: "1호선",
    verified: false,
  },
  osanCollege: {
    name: "오산대",
    lat: 37.1691,
    lng: 127.0548,
    line: "1호선",
    verified: false,
  },
  osan: {
    name: "오산",
    lat: 37.1459,
    lng: 127.0667,
    line: "1호선",
    verified: false,
  },
  jinwi: {
    name: "진위",
    lat: 37.1094,
    lng: 127.0614,
    line: "1호선",
    verified: false,
  },
  songtan: {
    name: "송탄",
    lat: 37.0754,
    lng: 127.0549,
    line: "1호선",
    verified: false,
  },
  seojeongri: {
    name: "서정리",
    lat: 37.0566,
    lng: 127.0526,
    line: "1호선",
    verified: false,
  },
  pyeongtaekJije: {
    name: "평택지제",
    lat: 37.0189,
    lng: 127.0703,
    line: "1호선",
    verified: false,
  },
  pyeongtaek: {
    name: "평택",
    lat: 36.991,
    lng: 127.0857,
    line: "1호선",
    verified: false,
  },
  seonghwan: {
    name: "성환",
    lat: 36.9161,
    lng: 127.1268,
    line: "1호선",
    verified: false,
  },
  jiksan: {
    name: "직산",
    lat: 36.8704,
    lng: 127.1438,
    line: "1호선",
    verified: false,
  },
  dujeong: {
    name: "두정",
    lat: 36.8337,
    lng: 127.1487,
    line: "1호선",
    verified: false,
  },
  cheonan: {
    name: "천안",
    lat: 36.8095,
    lng: 127.1462,
    line: "1호선",
    verified: false,
  },
  bongmyeong: {
    name: "봉명",
    lat: 36.7998,
    lng: 127.1373,
    line: "1호선",
    verified: false,
  },
  ssangyong: {
    name: "쌍용",
    lat: 36.7947,
    lng: 127.1239,
    line: "1호선",
    verified: false,
  },
  asan: {
    name: "아산",
    lat: 36.7904,
    lng: 127.1051,
    line: "1호선",
    verified: false,
  },
  tangjeong: {
    name: "탕정",
    lat: 36.7884,
    lng: 127.0851,
    line: "1호선",
    verified: false,
  },
  baebang: {
    name: "배방",
    lat: 36.7774,
    lng: 127.0528,
    line: "1호선",
    verified: false,
  },
  onyangoncheon: {
    name: "온양온천",
    lat: 36.7806,
    lng: 127.0031,
    line: "1호선",
    verified: false,
  },
  sinchang: {
    name: "신창",
    lat: 36.7696,
    lng: 126.9511,
    line: "1호선",
    verified: false,
  },
  //1호션 경인선 구간
  guil: {
    name: "구일",
    lat: 37.4967,
    lng: 126.8708,
    line: "1호선",
    verified: false,
  },
  gaebong: {
    name: "개봉",
    lat: 37.4946,
    lng: 126.8586,
    line: "1호선",
    verified: false,
  },
  oryudong: {
    name: "오류동",
    lat: 37.4945,
    lng: 126.8453,
    line: "1호선",
    verified: false,
  },
  onsu: {
    name: "온수",
    lat: 37.4923,
    lng: 126.8238,
    line: "1호선",
    verified: false,
  },
  yeokgok: {
    name: "역곡",
    lat: 37.4851,
    lng: 126.8116,
    line: "1호선",
    verified: false,
  },
  sosa: {
    name: "소사",
    lat: 37.4828,
    lng: 126.7952,
    line: "1호선",
    verified: false,
  },
  bucheon: {
    name: "부천",
    lat: 37.4841,
    lng: 126.7827,
    line: "1호선",
    verified: false,
  },
  jungdong: {
    name: "중동",
    lat: 37.4865,
    lng: 126.7634,
    line: "1호선",
    verified: false,
  },
  songnae: {
    name: "송내",
    lat: 37.4876,
    lng: 126.7535,
    line: "1호선",
    verified: false,
  },
  bugae: {
    name: "부개",
    lat: 37.4883,
    lng: 126.741,
    line: "1호선",
    verified: false,
  },
  bupyeong: {
    name: "부평",
    lat: 37.4895,
    lng: 126.7241,
    line: "1호선",
    verified: false,
  },
  baegun: {
    name: "백운",
    lat: 37.4918,
    lng: 126.7077,
    line: "1호선",
    verified: false,
  },
  dongam: {
    name: "동암",
    lat: 37.4929,
    lng: 126.6914,
    line: "1호선",
    verified: false,
  },
  ganseok: {
    name: "간석",
    lat: 37.4647,
    lng: 126.6934,
    line: "1호선",
    verified: false,
  },
  juan: {
    name: "주안",
    lat: 37.4648,
    lng: 126.6798,
    line: "1호선",
    verified: false,
  },
  dohwa: {
    name: "도화",
    lat: 37.4659,
    lng: 126.6685,
    line: "1호선",
    verified: false,
  },
  jemulpo: {
    name: "제물포",
    lat: 37.4665,
    lng: 126.6568,
    line: "1호선",
    verified: false,
  },
  dowon: {
    name: "도원",
    lat: 37.4684,
    lng: 126.643,
    line: "1호선",
    verified: false,
  },
  dongincheon: {
    name: "동인천",
    lat: 37.4754,
    lng: 126.6329,
    line: "1호선",
    verified: false,
  },
  incheon: {
    name: "인천",
    lat: 37.476,
    lng: 126.6169,
    line: "1호선",
    verified: false,
  },
  //1호선 광명
  gwangmyeong: {
    name: "광명",
    lat: 37.1,
    lng: 126.1,
    line: "1호선",
    verified: false,
  },
  //1호선 서동탄
  seodongtan: {
    name: "서동탄",
    lat: 37.1996,
    lng: 127.0543,
    line: "1호선",
    verified: false,
  },

  // === 2호선 역 데이터 (신규 추가) ===
  // 본선 (순환선 주요역)
  cityhall: {
    name: "시청",
    lat: 37.5647,
    lng: 126.9771,
    line: "2호선",
    verified: false,
  },
  euljiro3: {
    name: "을지로3가",
    lat: 37.5663,
    lng: 126.9918,
    line: "2호선",
    verified: false,
  },
  dongdaemun_history: {
    name: "동대문역사문화공원",
    lat: 37.5657,
    lng: 127.0079,
    line: "2호선",
    verified: false,
  },
  wangsimni: {
    name: "왕십리",
    lat: 37.5615,
    lng: 127.0371,
    line: "2호선",
    verified: false,
  },
  seongsu: {
    name: "성수",
    lat: 37.5446,
    lng: 127.0559,
    line: "2호선",
    verified: false,
  },
  jamsil: {
    name: "잠실",
    lat: 37.5133,
    lng: 127.1001,
    line: "2호선",
    verified: false,
  },
  samseong: {
    name: "삼성",
    lat: 37.5088,
    lng: 127.0632,
    line: "2호선",
    verified: false,
  },
  gangnam: {
    name: "강남",
    lat: 37.4979,
    lng: 127.0276,
    line: "2호선",
    verified: false,
  },
  교대: {
    name: "교대",
    lat: 37.4934,
    lng: 127.0142,
    line: "2호선",
    verified: false,
  },
  sadang: {
    name: "사당",
    lat: 37.4765,
    lng: 126.9816,
    line: "2호선",
    verified: false,
  },
  sindorim: {
    name: "신도림",
    lat: 37.5087,
    lng: 126.8913,
    line: "2호선",
    verified: false,
  },
  hongdae: {
    name: "홍대입구",
    lat: 37.5575,
    lng: 126.9245,
    line: "2호선",
    verified: false,
  },
  sinchon: {
    name: "신촌",
    lat: 37.5551,
    lng: 126.9369,
    line: "2호선",
    verified: false,
  },

  // 성수지선
  yongdap: {
    name: "용답",
    lat: 37.5619,
    lng: 127.0508,
    line: "2호선",
    verified: false,
  },
  sinseoldong: {
    name: "신설동",
    lat: 37.5753,
    lng: 127.0248,
    line: "2호선",
    verified: false,
  },

  // 신정지선
  kkachi_san: {
    name: "까치산",
    lat: 37.5318,
    lng: 126.8467,
    line: "2호선",
    verified: false,
  },
};

/**
 * 호선/계통별 노선 구성 정보
 */
const lineRoutes = {
  line1: {
    main: [
      "yeoncheon",
      "jeongok",
      "cheongsan",
      "soyosan",
      "dongducheon",
      "bosan",
      "dongducheonJungang",
      "jihaeng",
      "deokjeong",
      "deokgye",
      "yangju",
      "nokyang",
      "ganeung",
      "uijeongbu",
      "hoeryong",
      "mangwolsa",
      "dobongsan",
      "dobong",
      "banghak",
      "changdong",
      "nokcheon",
      "wolgye",
      "kwangwoonUniv",
      "seokgye",
      "sinimun",
      "oedaeap",
      "hoegi",
      "cheongnyangni",
      "jegiDong",
      "sinseolDong",
      "dongmyo",
      "dongdaemun",
      "jongno5ga",
      "jongno3ga",
      "jonggak",
      "cityhall",
      "seoulStation",
      "namyeong",
      "yongsan",
      "noryangjin",
      "daebang",
      "singil",
      "yeongdeungpo",
      "sindorim",
      "guro",
      "gasanDigitalComplex",
      "doksan",
      "geumcheonGuOffice",
      "seoksu",
      "gwanak",
      "anyang",
      "myeonghak",
      "geumjeong",
      "gunpo",
      "dangjeong",
      "uiwang",
      "sungkyunkwanUniv",
      "hwaseo",
      "suwon",
      "seryu",
      "byeongjeom",
      "sema",
      "osanCollege",
      "osan",
      "jinwi",
      "songtan",
      "seojeongri",
      "pyeongtaekJije",
      "pyeongtaek",
      "seonghwan",
      "jiksan",
      "dujeong",
      "cheonan",
      "bongmyeong",
      "ssangyong",
      "asan",
      "tangjeong",
      "baebang",
      "onyangoncheon",
      "sinchang",
    ],
    incheon: [
      "guro",
      "guil",
      "gaebong",
      "oryudong",
      "onsu",
      "yeokgok",
      "sosa",
      "bucheon",
      "jungdong",
      "songnae",
      "bugae",
      "bupyeong",
      "baegun",
      "dongam",
      "ganseok",
      "juan",
      "dohwa",
      "jemulpo",
      "dowon",
      "dongincheon",
      "incheon",
    ],
    gwangmyeong: ["geumcheonGuOffice", "gwangmyeong"],
    seodongtan: ["byeongjeom", "seodongtan"],
  },
  line2: {
    main: [
      "cityhall",
      "euljiro3",
      "dongdaemun_history",
      "wangsimni",
      "seongsu",
      "jamsil",
      "samseong",
      "gangnam",
      "sadang",
      "sindorim",
      "hongdae",
      "sinchon",
      "cityhall",
    ],
    seongsu_branch: ["seongsu", "yongdap", "sinseoldong"],
    sinjeong_branch: ["sindorim", "kkachi_san"],
  },
};
